schema_version: 1

context:
  version: "0.7.3"

package:
  name: validatedata
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/v/validatedata/validatedata-${{ version }}.tar.gz
  sha256: 98008383af29c7d352dde09dc2080111d8c65b61b24fd1071f70cf50ff06934f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - python-dateutil

tests:
  - python:
      imports:
        - validatedata
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: An easier way to validate data in python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Edward-K1/validatedata
  documentation: https://validatedata.readthedocs.io

extra:
  recipe-maintainers:
    - thewchan
