schema_version: 1

context:
  version: "0.7.1"

package:
  name: validatedata
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/v/validatedata/validatedata-${{ version }}.tar.gz
  sha256: 4f28c4597d6259926eda90b9cab1796a9a6358dc9d0b8a2a12c4a0e193c9c68b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - python-dateutil

tests:
  - python:
      imports:
        - validatedata
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: An easier way to validate data in python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Edward-K1/validatedata
  documentation: https://validatedata.readthedocs.io

extra:
  recipe-maintainers:
    - thewchan
